
# #
# # x = 5
# # y = 10
# # eval(input("Enter a number"))
# # message = "number * 2"
# # print(message)
# # total = 5 + 10
# # print(total)
# # z = x + y
# # print(z)
# # my_1st_name = "John"
# # print(my_1st_name)
# # AfricanCountries=["nigeria","Ghana","Togo"]
# # print(AfricanCountries
# # colors=["Red","Blue","Black","Green","white"]
# # print(colors[0])
# # print(colors[1])
# # print(colors[-1])
# # print(colors[1:3])
# # print(colors[1:4+1])
# # print(colors[2:])
# # print(colors[:3])
# # print(colors[-5:3])
# # names = ["David","Abubaker","Amina"]
# # names = [0:2] = ["Nimi","Sidi"]
# # names.append("Ibrahim")
# # names.insert(1,"Hamud")
# # RemoveItem from a  list
# # studentDetails  = {"name": "David","age": 100, "hubby": "coding"}
# # print(studentDetails)
# # studentDetails["age"]=11
# # studentDetails.update({"name":"David Enabs"})
# # studentDetails["class"] = "Play Tech"
# # studentDetails.update({"favourite_food"})
# #         "Class1":"python",
# #       }
# #       "two":  {
# # Operators
# # types of operator
# #  Arithmetic operator(e.g +,-,/,*,%,**,//)
# #  Assignment Operator (e.g =,+=,-=,*=,/=,!=)
# # TASK1 08/08/2023
# # create program that accept three number from the user,store the number in their different variable and check with
# # number is the greatest and output the number
# # TASK 2
# # write a program to check if a user is qualified to vote or not,assuming the
# # qualified voting age is 18 and above.Note: you are to accept the age from the user.
# # TASK1
# # num1 = eval(input("Enter first number:"))
# # num2 = eval(input("Enter second number:"))
# # num3 = eval(input("Enter third number:"))
# # if num1 > num2:
# #     print("The first number is the greatest")
# # elif num1 < num2:
# #     print("The second is the greatest")
# # elif num3 > num1 + num2:
# #     print("The third number is the greatest
# # TASK2
# # VotingAgeRequirement = 18
# # UnacceptedAgeToVote = 12
# # VotingForm = eval(input('Enter your present age:'))
# # if VotingForm >= VotingAgeRequirement:
# #     print('congratulation!you are qualified to vote')
# # elif  VotingForm <= VotingAgeRequirement:
# #     print('Opps! looks like you are too young too young to vote')
#
# #1
# # K
# #
# # write a program to accept a peson's year of birthday and tell the person their current age
#  #  TASK1
#
#
# #  randomnumber = {2,4,5,2,4,2,56,1,3,4,6,8,9,4,5,7,8,4,2,2}
# # task2
# #  write a program to ask a user to pick a number,check if the number is among the list of
# #  numbers above,if the user inputted is in the list,tell the user,they picked correctly else they picked wrongly.
# #
# # DateOfBirth = eval(input('Enter your date of birth:'))
# # PresentYear = 2023
# # Result = PresentYear - DateOfBirth
# # Message = (f'You are{Result} years old')
# # print(Message)
# #
# # for i in range(1, 11):
# #     value = eval(input("Enter number"  + str(i) + ": "))
# #     listOfNumbers.append(value)
# #
# #
# # lowestNumber = listofnumber[0]
# # highestNumber = listofNumber
# #
# # for i
# # x = "David"
# # y = "Enabs"
# # name = x + y
# # print(name)
# #
# # fname = input("Your first name:")
# # lname = input("Your last name:")
# # age = eval(input("Your age:"))
# # message = "Hello " + fname + " " + lname +" you are " +str(age) + "years old!"
# # print(message)
# # message = f"Hello (fname),(lname), your age is (age)"
# # message = "Hello {} {}, your age is {}".format(fname, lname,age)
# #
# # xyz = f'The number is {20}'
# # print(xyz)
# #
# # Number = {6,3,8,4,2,3,5,4,3,4,3,2,6,8,99,8,8,4,2}
# # lengthofNumber = len()
# # write a program to copy the items from this list fruit = ["apple", "Banana","cherry"]to a new list.you are to create the.
# # write a program to accept 10 number
# #
# #  name="classwork"
# # print(name)
# # carname="bugatti"
# # print(carname)
# # x=58
# # print(x)
# # x = 5
# # y = 10
# # total = 5 + 10
# # print(total)
# # z = x + y
# # print(z)
# # my_1st_name = "John"
# # print(my_1st_name)
# # AfricanCountries=["nigeria","Ghana","Togo"]
# # print(AfricanCountries
# # colors=["Red","Blue","Black","Green","white"]
# # print(colors[0])
# # print(colors[1])
# # print(colors[-1])
# # print(colors[1:3])
# # print(colors[1:4+1])
# # print(colors[2:])
# # print(colors[:3])
# # print(colors[-5:3])
# # names = ["David","Abubaker","Amina"]
# # names = [0:2] = ["Nimi","Sidi"]
# # names.append("Ibrahim")
# # names.insert(1,"Hamud")
# # RemoveItem from a  list
# # studentDetails  = {"name": "David","age": 100, "hubby": "coding"}
# # print(studentDetails)
# # studentDetails["age"]=11
# # studentDetails.update({"name":"David Enabs"})
# # studentDetails["class"] = "Play Tech"
# # studentDetails.update({"favourite_food"})
# #         "Class1":"python",
# #       }
# #       "two":  {
# # Operators
# # types of operator
# #  Arithmetic operator(e.g +,-,/,*,%,**,//)
# #  Assignment Operator (e.g =,+=,-=,*=,/=,!=)
# # TASK1 08/08/2023
# # create program that accept three number from the user,store the number in their different variable and check with
# # number is the greatest and output the number
# # TASK 2
# # write a program to check if a user is qualified to vote or not,assuming the
# # qualified voting age is 18 and above.Note: you are to accept the age from the user.
# # TASK1
# # num1 = eval(input("Enter first number:"))
# # num2 = eval(input("Enter second number:"))
# # num3 = eval(input("Enter third number:"))
# # if num1 > num2:
# #     print("The first number is the greatest")
# # elif num1 < num2:
# #     print("The second is the greatest")
# # elif num3 > num1 + num2:
# #     print("The third number is the greatest
# # TASK2
# # VotingAgeRequirement = 18
# # UnacceptedAgeToVote = 12
# # VotingForm = eval(input('Enter your present age:'))
# # if VotingForm >= VotingAgeRequirement:
# #     print('congratulation!you are qualified to vote')
# # elif  VotingForm <= VotingAgeRequirement:
# #     print('Opps! looks like you are too young too young to vote')
#
# #1
# # K
# #
# # write a program to accept a peson's year of birthday and tell the person their current age
#  #  TASK1
#
#
# #  randomnumber = {2,4,5,2,4,2,56,1,3,4,6,8,9,4,5,7,8,4,2,2}
# # task2
# #  write a program to ask a user to pick a number,check if the number is among the list of
# #  numbers above,if the user inputted is in the list,tell the user,they picked correctly else they picked wrongly.
# #
# # DateOfBirth = eval(input('Enter your date of birth:'))
# # PresentYear = 2023
# # Result = PresentYear - DateOfBirth
# # Message = (f'You are{Result} years old')
# # print(Message)
# #
# # for i in range(1, 11):
# #     value = eval(input("Enter number"  + str(i) + ": "))
# #     listOfNumbers.append(value)
# #
# #
# # lowestNumber = listofnumber[0]
# # highestNumber = listofNumber
# #
# # for i
# # x = "David"
# # y = "Enabs"
# # name = x + y
# # print(name)
# #
# # fname = input("Your first name:")
# # lname = input("Your last name:")
# # age = eval(input("Your age:"))
# # message = "Hello " + fname + " " + lname +" you are " +str(age) + "years old!"
# # print(message)
# # message = f"Hello (fname),(lname), your age is (age)"
# # message = "Hello {} {}, your age is {}".format(fname, lname,age)
# #
# # xyz = f'The number is {20}'
# # print(xyz)
# # Number = {6,3,8,4,2,3,5,4,3,4,3,2,6,8,99,8,8,4,2}
# # lengthofNumber = len()
# # write a program to copy the items from this list fruit = ["apple", "Banana","cherry"]to a new list.you are to create the.
# # write a program to accept 10 number
# # listofnumbers =[]
# #
# #
# #
# # for index in range(10):
# # Number =eval(input("Enter a number"))
# # for index in range(10):
# #     number =eval(input("Enter a number: "))
# #     listofnumbers.append(number)
# #
# # print(f"Item in the list are: {listofnumbers}")
# #
# # count = 0
# # evenNumberList =[]
# # for index in range(10):
# #     if listofnumbers[index] % 2 == 0:
# #         count += 1
# #         evenNumberList.append(listofnumbers[index])
# #
# # print(f"The total even number you enter is: {count}")
# # print(f"The even number are: {evenNumberList}")
#
# # def add_numbers(x, y):
# #     result = x+y
# #     print(result)
# # #
# #
# # n1 = eval(input("Numbers 1 again:"))
# # n2 = eval(input("Numbers 2 again:"))
# # add_numbers(n1, n2)
# #
# #
# # #
# # # def add_numbers(x, y):
# # #     result = x+y
# # #   return result
# #
# #
# # n1 = eval(input("Numbers 1 again:"))
# # n2 = eval(input("Numbers 2 again:"))
# # add_numbers(n1, n2)
# # n1= eval(input("Numbers 1 again:"))
# # n2 = eval(input("Numbers 2 again:"))
# # r = add_numbers(n1, n2)
# # print(f"The return value from the function is {r}")
# print("******************************* ")
# print("**** MY PYTHON ")
#
#
#
#
#
#
